In [3]:
import sys
sys.path.insert(1,'../NanoGenCat/bcnm/')

from bcn_wulff_new import *

from ase.atoms import Atoms
from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer 

lattice =  np.array(  [[0.000000000000E+00 ,  0.210850000000E+01 ,  0.210850000000E+01],
   [0.210850000000E+01 ,  0.000000000000E+00  , 0.210850000000E+01],
   [0.210850000000E+01 ,  0.210850000000E+01 ,  0.000000000000E+00]])
structure = Structure(lattice,['Mg','O'],[[0.,0.,0.],[0.5,0.5,0.5]])
symbol = AseAtomsAdaptor().get_atoms(structure)

surfaces = [[0, 0, 1],[0, 0, 1]]

surface_energies_Ni = surface_energies_Ni = {
    (3, 2, 0): 2.3869,
    (1, 1, 0): 2.2862,
    (3, 1, 0): 2.3964,
    (2, 1, 0): 2.3969,
    (3, 3, 2): 2.0944,
    (1, 0, 0): 2.2084,
    (2, 1, 1): 2.2353,
    (3, 2, 2): 2.1242,
    (3, 2, 1): 2.3183,
    (2, 2, 1): 2.1732,
    (3, 3, 1): 2.2288,
    (3, 1, 1): 2.3039,
    (1, 1, 1): 1.9235,
}

surfaces = surface_energies_Ni.keys()
energies = surface_energies_Ni.values()

structure = Structure(lattice,['Mg','O'],[[0.,0.,0.],[0.5,0.5,0.5]])
structure = SpacegroupAnalyzer(structure).get_conventional_standard_structure()
structure_init = copy.deepcopy(structure)
nano = Nanoparticle(structure)
nano = nano.make_stoichiometric(surfaces,energies,size=300)
view(AseAtomsAdaptor().get_atoms(nano))

0.4971888065338135
0.002117156982421875
0.0024847984313964844
0.0023059844970703125
0.002269744873046875
0.002276897430419922
0.002290010452270508
0.0022330284118652344
0.002460956573486328
0.002263784408569336
0.0022780895233154297
0.0024247169494628906
0.0022537708282470703
0.0022993087768554688
0.002218008041381836
0.002177000045776367
0.0022208690643310547
0.0022430419921875
0.0022280216217041016
0.002277851104736328
0.002290964126586914
0.0023479461669921875
0.0023107528686523438
0.0022389888763427734
0.002277851104736328
0.0021910667419433594
0.002249002456665039
0.0022258758544921875
0.00214385986328125
0.0022749900817871094
0.0022399425506591797
0.0022611618041992188
0.002274036407470703
0.0024008750915527344
0.002294778823852539
0.00222015380859375
0.002270936965942383
0.0023009777069091797
0.0023260116577148438
0.002309083938598633
0.002297639846801758
0.002317190170288086
0.002268075942993164
0.002232789993286133
0.0023069381713867188
0.0022940635681152344
0.0022711753845214

<Popen: returncode: None args: ['/Users/brunocamino/miniconda3/envs/test_env...>

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [46]:
nano.remove_sites([0])

In [101]:
# Position of atoms types in the structure
atoms_type_site = []
for atom in np.unique(structure.atomic_numbers):
    atoms_type_site.append(np.where(structure.atomic_numbers == atom)[0])    

In [195]:

atom_symbols = list(nano.composition.reduced_composition.as_dict().keys())
atomic_number = np.array([element(atom_symbol).atomic_number for atom_symbol in atom_symbols])

atoms_type_site = []
for atom in atomic_number:
    atoms_type_site.append(np.where(structure.atomic_numbers == atom)[0])    

atoms_type_site

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
        74, 75, 76, 77, 78, 79])]

In [220]:
structure = Structure(lattice,['Mg','O'],[[0.,0.,0.],[0.5,0.5,0.5]])
structure = SpacegroupAnalyzer(structure).get_conventional_standard_structure()
structure_init = copy.deepcopy(structure)
nano = Nanoparticle(structure)
nano = nano.make_stoichiometric(surfaces,energies,size=100)
nano.remove_sites([0])
atoms_type_site = []
for atom in atomic_number:
    atoms_type_site.append(np.where(structure.atomic_numbers == atom)[0])    

nano_remove_array = np.array([1,0])

In [221]:
nano.composition

Comp: Mg39 O40

In [224]:
coord_vector = get_coordination(structure)

stoich_method = 'combinatory'

for i,atoms in enumerate(nano_remove_array):
    if atoms > 0:     
        coord_sorted = np.sort(coord_vector[atoms_type_site[i]])
        print(coord_sorted)
        unique_coord, count_unique = np.unique(coord_sorted, return_counts=True)
        print(np.unique(coord_sorted, return_counts=True))
        # This is the beginning of the combinatorial analysis
        if count_unique[0] < atoms:
            index = atoms
            for j in count_unique:
                if j < index:
                    atoms_to_remove = np.argsort(coord_vector[atoms_type_site[i]])[0:count_unique]
        elif count_unique[0] > atoms:
            # remove the top ones in the array
            if stoich_method == 'combinatory':
                combinations = np.array(list(itertools.product([0, 1], repeat=atoms)))
            else:
                atoms_to_remove = np.argsort(coord_vector[atoms_type_site[i]])[0:atoms]
            # do all the combinations
            #import itertools
            #X = np.array(list(itertools.product([0, 1], repeat=18)))
            #np.where(np.sum(X,axis=1) == 2)
            
            # add symmetry analysis
structure.remove_sites(atoms_to_remove)


[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6]
(array([3, 6]), array([23, 16]))


In [231]:
import itertools
X = np.array(list(itertools.product([0, 1], repeat=count_unique[0])))
np.where(np.sum(X,axis=1) == 1)


(array([      1,       2,       4,       8,      16,      32,      64,
            128,     256,     512,    1024,    2048,    4096,    8192,
          16384,   32768,   65536,  131072,  262144,  524288, 1048576,
        2097152, 4194304]),)

In [99]:
def get_coordination(structure):
    """
    function that calculates the coordination of the crystal
    Args:
        structure: pymatgen Structure object
        atoms(atoms): atoms object for the nano
    """

    # Position of atoms types in the structure
    atoms_type_site = []
    for atom in np.unique(structure.atomic_numbers):
        atoms_type_site.append(np.where(structure.atomic_numbers == atom)[0])

    # Shells of neighbours. It's a 2-dimensional array. 
    # The first index is the atom type, the second are
    # the shells for that atom type
    shells = []
    for atom_type in np.unique(structure.atomic_numbers):
        shells.append(np.unique(np.round(structure.distance_matrix[np.where(np.array(structure.atomic_numbers) == atom_type)[0],:],4)))

    # Think about this if the structure is homogeneous
    '''if np.unique(shells,axis=0).shape[0] == 1:
        shells = np.unique(shells,axis=0)'''

    coord_vector  = np.zeros(structure.num_sites,dtype=int)
    
    for i,atoms in enumerate(atoms_type_site):
        for atom in atoms:
            coord_vector[atom] = np.sum(np.round(structure.distance_matrix[atom,:],5) == shells[i][1])

    return coord_vector

In [ ]:
chemicalSpecies: [Mg,O]
spaceGroupNumber: 225
charges: [2,-2]

basis:
 - [0.0, 0.0, 0.0]
 - [0.5, 0.5,0.5]
cellDimension: [4.211,4.211,4.211, 90, 90, 90]

surfaceEnergy: [0.86,0.86]
surfaces: 
  - [0, 0, 1]
  - [0, 0, 1]

nanoparticleSize: 8
sizeRange: 3
step: 1

centering: manualShift
numberOfShifts: 1
shifts:
 - [0.25,0.25,0.25]

onlyNp0: True
stoichiometric : True

In [ ]:

bcn_wulff_construction(symbol, surfaces, energies, size, structure,
    rounding='closest',latticeconstant=None, maxiter=100,
    center=[0.,0.,0.],stoichiometryMethod=1,np0=False,wl_method='hybridMethod',
    sampleSize=1000,totalReduced=False,coordinationLimit='half',polar=False,
    termNature='non-metal',neutralize=False,inertiaMoment=False,debug=0):